### ISSUE TITLE
Run the tartiflette code 

### ISSUE THREAD

**Issue by hayatbellafkih** [romain-fontugne/tartiflette#1]
Hello,

I am interested to run the code source, by reading the README file, i can't see how i can do this! I am a student, I am interested to reproduce the results of "Pinpointing Delay and Forwarding Anomalies Using Large-Scale Traceroute Measurements".

What is the objectif of the command:

zcat 2015-06-0*.gz | grep -f scripts/msmIds.txt | mongoimport --db atlas --collection traceroute

Thanks in advance

**Comment by romain-fontugne** [comment]
Hi, 

Sorry the Readme was pretty bad. I have added more information there. Let me know if it helps. I haven't touch this code for some time, so I might have missed a few things.

**Comment by romain-fontugne** [comment]
Hi,

Thanks, let me know if you have other troubles
